Create xBee_driver low-level library
BDI-ENIB/vive-tracker pull request #10
Opened 2019-12-01 17:25 UTC by Neopibox

This contribution contains the low-level library to allow the PSoC to communicate with the local xBee, using UART protocol (at 921000 bauds) and the xBee API frames. It only implements, for now, RX and TX frames with 16-bits adressing.

It's mandatory to implement Tonnerre's protocol, as requested in issue #4.

It is compatible with xBee S3, as long as they are flashed with 802.15.4 firmware, and configured properly.

2019-12-01 18:04 UTC, nils-van-zuijlen requested changes

2019-12-01 18:04 UTC, nils-van-zuijlen commented on code/ViveBeacons/ViveBeacons.cydsn/XBee_driver.c
> + * ========================================
Est-il possible de mettre le BDI ou toi dans cet en-tete ? Et de specifier la licence.
Il faut d'ailleurs en choisir une. Je propose la AGPL.

2019-12-01 18:04 UTC, nils-van-zuijlen commented on code/ViveBeacons/ViveBeacons.cydsn/XBee_driver.c
> +    UART_XBEE_Start();
Est-ce que ce ne serait pas mieux en passant le pointeur en paramètre de la macro ?

2019-12-01 18:04 UTC, nils-van-zuijlen commented on code/ViveBeacons/ViveBeacons.cydsn/XBee_driver.c
> +    UART_XBEE_Start();
Ou alors c'est qu'il n'est pas du tout utilisé ?
Et alors pourquoi est-il un paramètre ?

2019-12-01 18:04 UTC, nils-van-zuijlen commented on code/ViveBeacons/ViveBeacons.cydsn/XBee_driver.h
> + * ========================================
Idem, © et licence

2019-12-01 18:04 UTC, nils-van-zuijlen commented on code/ViveBeacons/ViveBeacons.cydsn/XBee_driver_unit_tests.c
> + * ========================================
Idem, © et licence

2019-12-01 18:04 UTC, nils-van-zuijlen commented on code/ViveBeacons/ViveBeacons.cydsn/XBee_driver_unit_tests.c
> +    between each packet (depend on the baudrate defined on the UART link).
Il y a moyen d'empécher le spam ? avec un timer ou qqch du genre ?

2019-12-01 18:04 UTC, nils-van-zuijlen commented on code/ViveBeacons/ViveBeacons.cydsn/XBee_driver_unit_tests.h
> + * ========================================
Re, © et licence

2019-12-01 19:19 UTC, Neopibox commented on code/ViveBeacons/ViveBeacons.cydsn/XBee_driver.c
> + * ========================================
En soit, cet entête existe dans tous les fichiers créés à partir de PSoC Creator par défaut et je n'ai jamais réellement pris la peine de le changer.

Je considère néanmoins que mes contributions relève du logiciel libre, donc il est, en effet, nécessaire de préciser la licence. AGPL, c'est très bien, vu la notion de réseau qu'apporte le protocole Tonnerre.

2019-12-01 19:21 UTC, Neopibox commented on code/ViveBeacons/ViveBeacons.cydsn/XBee_driver.c
> +    UART_XBEE_Start();
C'est un paramètre inutilisé dans ce cas précis.
L'idée est de conserver la même logique pour tous les modules du firmware (c'est, en quelque sorte, le principe de l'orienté objet à la Python).
Si, dans le futur, cette fonction est modifiée et que le paramètre est nécessaire, les codes utilisant cette bibliothèque seront donc déjà compatibles.

2019-12-01 19:30 UTC, Neopibox commented on code/ViveBeacons/ViveBeacons.cydsn/XBee_driver_unit_tests.c
> +    between each packet (depend on the baudrate defined on the UART link).
Ce test unitaire ne fait que renvoyer l'information qu'on lui donne, au xBee n°0. Lors du déroulement du test, il faut juste veiller à ne pas spammer le xBee testé plus que nécessaire.
Je dirais que c'est, principalement, une limitation du lien radio entre xBee et non le lien UART, depuis qu'il a été boosté à 921000 bauds.

2019-12-02 00:53 UTC, nils-van-zuijlen commented on code/ViveBeacons/ViveBeacons.cydsn/XBee_driver.c
> + * ========================================
Ok, #11 
La modification sera à faire ici seulement si la PR qui correspondra est merge avant celle-ci.

2019-12-02 00:54 UTC, nils-van-zuijlen commented on code/ViveBeacons/ViveBeacons.cydsn/XBee_driver.c
> +    UART_XBEE_Start();
Ok, j'apprécie le future-proofing.

2019-12-04 08:55 UTC, nils-van-zuijlen approved these changes

2019-12-04 08:56 UTC, merged